name: libsignal_protocol_dart
description: Signal Protocol libray for Dart native and Flutter, pure Dart implementation of the the Signal Protocol
version: 0.1.1
homepage: https://github.com/MixinNetwork/libsignal_protocol_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cryptography: ^1.4.1
  protobuf: ^1.0.1
  convert: ^2.1.1
  optional: ^5.0.0
  tuple: ^1.0.3
  dartx: ^0.5.0
  fixnum: ^0.10.11
  collection: ^1.14.13
  ed25519_edwards: ^0.0.4

dev_dependencies:
  test: ^1.15.1
  pedantic: ^1.9.2
