name: libsignal_protocol_dart
description: signal protocol
version: 0.0.1
author:
homepage: https://github.com/MixinNetwork/libsignal_protocol_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cryptography: ^1.4.0
  protobuf: ^1.0.1
  convert: ^2.1.1
  optional: ^4.1.0
  crypto: ^2.1.5
  tuple: ^1.0.3
  dartx: ^0.4.1
  ffi: ^0.1.3
  pointycastle:
    git: git@github.com:bcgit/pc-dart.git

dev_dependencies:
  test: ^1.14.2
  pedantic: ^1.9.0
